### ISSUE TITLE
Offspring crashing after updating to Java RE 8u5

### ISSUE THREAD

**Issue by ShawnLeary** [incentivetoken/offspring#17]
Offspring immediately crashes upon launch and refers to a log file.  I'm guessing its not ready for Java 8?

**Comment by ShawnLeary** [comment]
Mac OS latest Mavericks. <a href="https://overview.mail.yahoo.com?.src=iOS"><br/><br/>Sent from Yahoo Mail for iPhone</a>

**Comment by incentivetoken** [comment]
I never tried it but Offspring should work with java 8. 
It could be NXT that does not work with java 8 or one of it's libraries. You could try if the default NXT client runs on your system (with java 8), if it doesn't then the problem is with NXT.

Without more details like what the error dialog says or a log file I can't help you out any further.

**Comment by ShawnLeary** [comment]
I can send you log file if that will help.<a href="https://overview.mail.yahoo.com?.src=iOS"><br/><br/>Sent from Yahoo Mail for iPhone</a>

**Comment by incentivetoken** [comment]
If you want to. Sure, that helps. If you prefer to keep it private that's possible to. Send it to incentivetoken on the gmail dot com domain and I'll have a look at it.

**Comment by ShawnLeary** [comment]
!SESSION 2014-06-25 21:16:27.944 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.6.0_65
java.vendor=Apple Inc.
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -clearPersistedState -Dosgi.signedcontent.support=authority -keyring /Users/xxxxxxx/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -clearPersistedState -Dosgi.signedcontent.support=authority -keyring /Users/xxxxxx/.eclipse_keyring -showlocation

!ENTRY org.eclipse.equinox.app 0 0 2014-06-25 21:16:31.513
!MESSAGE Product com.dgex.offspring.application.product could not be found.

!ENTRY org.eclipse.osgi 2 0 2014-06-25 21:16:32.328
!MESSAGE One or more bundles are not resolved because the following root constraints are not resolved:
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-06-25 21:16:32.328
!MESSAGE Bundle initial@reference:file:plugins/com.dgex.offspring.ui_1.0.0.201405192009.jar was not resolved.
!SUBENTRY 2 com.dgex.offspring.ui 2 0 2014-06-25 21:16:32.328
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-06-25 21:16:32.328
!MESSAGE Bundle initial@reference:file:plugins/org.bouncycastle_1.0.0.201405192009.jar was not resolved.
!SUBENTRY 2 org.bouncycastle 2 0 2014-06-25 21:16:32.328
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-06-25 21:16:32.328
!MESSAGE Bundle initial@reference:file:plugins/com.dgex.offspring.nxtCore_1.0.0.201405192009.jar was not resolved.
!SUBENTRY 2 com.dgex.offspring.nxtCore 2 0 2014-06-25 21:16:32.328
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".

!ENTRY org.eclipse.osgi 2 0 2014-06-25 21:16:32.348
!MESSAGE The following is a complete list of bundles which are not resolved, see the prior log entry for the root cause if it exists:
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-06-25 21:16:32.348
!MESSAGE Bundle com.dgex.offspring.application_1.0.0.201405192009 [2] was not resolved.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-06-25 21:16:32.348
!MESSAGE Missing required bundle com.dgex.offspring.swt_1.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-06-25 21:16:32.348
!MESSAGE Missing required bundle com.dgex.offspring.nxtCore_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-06-25 21:16:32.348
!MESSAGE Missing imported package com.dgex.offspring.nxtCore.core_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-06-25 21:16:32.348
!MESSAGE Missing imported package com.dgex.offspring.nxtCore.h2_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-06-25 21:16:32.348
!MESSAGE Missing imported package com.dgex.offspring.nxtCore.service_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-06-25 21:16:32.348
!MESSAGE Missing imported package com.dgex.offspring.providers.bitcoinaverage_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package com.dgex.offspring.providers.dgex_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package com.dgex.offspring.providers.service_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package com.dgex.offspring.providers.utils_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package com.dgex.offspring.trader.api_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package com.dgex.offspring.ui_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package com.dgex.offspring.ui.controls_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package com.dgex.offspring.update_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package com.dgex.offspring.user.service_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package nxt_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package nxt.peer_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package nxt.util_0.0.0.
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-06-25 21:16:32.349
!MESSAGE Bundle com.dgex.offspring.nxtCore_1.0.0.201405192009 [6] was not resolved.
!SUBENTRY 2 com.dgex.offspring.nxtCore 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package nxt_0.0.0.
!SUBENTRY 2 com.dgex.offspring.nxtCore 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package nxt.crypto_0.0.0.
!SUBENTRY 2 com.dgex.offspring.nxtCore 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package nxt.http_0.0.0.
!SUBENTRY 2 com.dgex.offspring.nxtCore 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package nxt.peer_0.0.0.
!SUBENTRY 2 com.dgex.offspring.nxtCore 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package nxt.user_0.0.0.
!SUBENTRY 2 com.dgex.offspring.nxtCore 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package nxt.util_0.0.0.
!SUBENTRY 2 com.dgex.offspring.nxtCore 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-06-25 21:16:32.349
!MESSAGE Bundle com.dgex.offspring.providers_1.0.0.201405192009 [7] was not resolved.
!SUBENTRY 2 com.dgex.offspring.providers 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing required bundle com.dgex.offspring.nxtCore_1.0.0.
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-06-25 21:16:32.349
!MESSAGE Bundle com.dgex.offspring.swt_1.0.0.201405192009 [8] was not resolved.
!SUBENTRY 2 com.dgex.offspring.swt 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package com.dgex.offspring.nxtCore.service_0.0.0.
!SUBENTRY 2 com.dgex.offspring.swt 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package com.dgex.offspring.swt.table_0.0.0.
!SUBENTRY 2 com.dgex.offspring.swt 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package com.dgex.offspring.user.service_0.0.0.
!SUBENTRY 2 com.dgex.offspring.swt 2 0 2014-06-25 21:16:32.349
!MESSAGE Missing imported package nxt.util_0.0.0.
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-06-25 21:16:32.350
!MESSAGE Bundle com.dgex.offspring.trader_1.0.0.201405192009 [9] was not resolved.
!SUBENTRY 2 com.dgex.offspring.trader 2 0 2014-06-25 21:16:32.350
!MESSAGE Missing required bundle com.dgex.offspring.swt_1.0.0.
!SUBENTRY 2 com.dgex.offspring.trader 2 0 2014-06-25 21:16:32.350
!MESSAGE Missing required bundle com.dgex.offspring.nxtCore_0.0.0.
!SUBENTRY 2 com.dgex.offspring.trader 2 0 2014-06-25 21:16:32.350
!MESSAGE Missing imported package com.dgex.offspring.nxtCore.core_0.0.0.
!SUBENTRY 2 com.dgex.offspring.trader 2 0 2014-06-25 21:16:32.350
!MESSAGE Missing imported package com.dgex.offspring.nxtCore.service_0.0.0.
!SUBENTRY 2 com.dgex.offspring.trader 2 0 2014-06-25 21:16:32.350
!MESSAGE Missing imported package com.dgex.offspring.providers.utils_0.0.0.
!SUBENTRY 2 com.dgex.offspring.trader 2 0 2014-06-25 21:16:32.350
!MESSAGE Missing imported package com.dgex.offspring.ui_0.0.0.
!SUBENTRY 2 com.dgex.offspring.trader 2 0 2014-06-25 21:16:32.350
!MESSAGE Missing imported package com.dgex.offspring.user.service_0.0.0.
!SUBENTRY 2 com.dgex.offspring.trader 2 0 2014-06-25 21:16:32.350
!MESSAGE Missing imported package nxt_0.0.0.
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-06-25 21:16:32.350
!MESSAGE Bundle com.dgex.offspring.ui_1.0.0.201405192009 [10] was not resolved.
!SUBENTRY 2 com.dgex.offspring.ui 2 0 2014-06-25 21:16:32.350
!MESSAGE Missing required bundle com.dgex.offspring.nxtCore_0.0.0.
!SUBENTRY 2 com.dgex.offspring.ui 2 0 2014-06-25 21:16:32.350
!MESSAGE Missing required bundle org.bouncycastle_1.0.0.
!SUBENTRY 2 com.dgex.offspring.ui 2 0 2014-06-25 21:16:32.350
!MESSAGE Missing imported package com.dgex.offspring.swt.table_0.0.0.
!SUBENTRY 2 com.dgex.offspring.ui 2 0 2014-06-25 21:16:32.350
!MESSAGE Missing imported package com.dgex.offspring.swt.wizard_0.0.0.
!SUBENTRY 2 com.dgex.offspring.ui 2 0 2014-06-25 21:16:32.350
!MESSAGE Missing imported package com.dgex.offspring.user.service_0.0.0.
!SUBENTRY 2 com.dgex.offspring.ui 2 0 2014-06-25 21:16:32.350
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-06-25 21:16:32.350
!MESSAGE Bundle com.dgex.offspring.update_1.0.0.201405192009 [11] was not resolved.
!SUBENTRY 2 com.dgex.offspring.update 2 0 2014-06-25 21:16:32.350
!MESSAGE Missing imported package com.dgex.offspring.nxtCore.service_0.0.0.
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-06-25 21:16:32.350
!MESSAGE Bundle com.dgex.offspring.user_1.0.0.201405192009 [12] was not resolved.
!SUBENTRY 2 com.dgex.offspring.user 2 0 2014-06-25 21:16:32.350
!MESSAGE Missing required bundle com.dgex.offspring.nxtCore_1.0.0.
!SUBENTRY 2 com.dgex.offspring.user 2 0 2014-06-25 21:16:32.350
!MESSAGE Missing required bundle com.dgex.offspring.nxtCore_0.0.0.
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-06-25 21:16:32.350
!MESSAGE Bundle org.bouncycastle_1.0.0.201405192009 [30] was not resolved.
!SUBENTRY 2 org.bouncycastle 2 0 2014-06-25 21:16:32.350
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".

!ENTRY org.eclipse.osgi 4 0 2014-06-25 21:16:32.354
!MESSAGE Application error
!STACK 1
org.eclipse.core.runtime.AssertionFailedException: null argument:applicationXMI argument missing
    at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:85)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application.loadApplicationModel(E4Application.java:342)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:238)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:144)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)

**Comment by incentivetoken** [comment]
This bit:

java.version=1.6.0_65

Says you are running java 6, not java 8.

**Comment by ShawnLeary** [comment]
I noticed that.  Apparently something isn't recognizing 1.8.  I am running offspring in windoze/parallels now so I am good to go.  NEM requires 1.8.  So I guess the ability for Offspring to see 1.8 could be an issue.  <a href="https://overview.mail.yahoo.com?.src=iOS"><br/><br/>Sent from Yahoo Mail for iPhone</a>

**Comment by incentivetoken** [comment]
Offspring uses the system default jre, yours is set to 1.6. Offspring does not do any recognizing of java versions.

Check your JAVA_HOME and PATH enviroment variables, you'll see they point to java 1.6. If you remove that Offspring will pick up java 1.8, and it might even work.

**Comment by ShawnLeary** [comment]
"You are trying to install Java 7 Update 60, however Java 8 Update 05 is already installed.
Visit java.com/newerversionexists for more information."

shawns-imac:~ xxxxxx$ java -version
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)
shawns-imac:~ xxxxxx$
